// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt8sDxSDkGACwsETE_4Tk05tblomTT4Iw',
    appId: '1:475132050298:web:665f95e7c79b4c2edcb4c3',
    messagingSenderId: '475132050298',
    projectId: 'minder-alert',
    authDomain: 'minder-alert.firebaseapp.com',
    storageBucket: 'minder-alert.appspot.com',
    measurementId: 'G-6NR70JV58V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvWNGoRYSIYxo3VqhI6sJuqiCElDtjOBw',
    appId: '1:475132050298:android:fc3d065920d54859dcb4c3',
    messagingSenderId: '475132050298',
    projectId: 'minder-alert',
    storageBucket: 'minder-alert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPnowrYBKGpDci610pbjyrkUBkqqieiRM',
    appId: '1:475132050298:ios:2693283ff86400bedcb4c3',
    messagingSenderId: '475132050298',
    projectId: 'minder-alert',
    storageBucket: 'minder-alert.appspot.com',
    androidClientId: '475132050298-o22cka269c4pisv6hjeghesl99p9chsa.apps.googleusercontent.com',
    iosClientId: '475132050298-0a6co0v9pftbmid6pv41ch8ov7614ih4.apps.googleusercontent.com',
    iosBundleId: 'com.example.medreminder',
  );
}
